const prod = process.env.NODE_ENV === "production";

// Regex patterns for classes that are composed/injected at runtime
// and cannot be detected by static content scanning.
const safelistPatterns = [
  // Bootstrap JS state
  /^modal/, /^dropdown/, /^collapse/, /^navbar/, /^fade/, /^show$/,
  // react-slick
  /^slick-/,
  // Phosphor icons
  /^ph/,
  // AOS
  /^aos-/, /^\[data-aos/,
  // Project dynamic utilities (built via template literals)
  /^hover-/, /^bg-main/, /^text-main/, /^border-main/,
  /^bg-gray/, /^text-gray/, /^bg-info/, /^bg-danger/, /^bg-warning/,
  /^text-info/, /^text-danger/, /^text-success/,
  // Bootstrap utility classes (safe — generated by SASS mixin, hard to enumerate)
  /^d-/, /^w-/, /^h-/, /^flex-/, /^align-/, /^justify-/, /^order-/,
  /^col-/, /^g-/, /^gy-/, /^gx-/,
  /^p[tblrsexy]?-/, /^m[tblrsexy]?-/, /^gap-/,
  /^fs-/, /^fw-/, /^lh-/, /^text-/,
  /^rounded/, /^border/, /^shadow/, /^overflow/, /^z-/, /^opacity-/,
  /^position-/, /^top-/, /^bottom-/, /^start-/, /^end-/,
  /^translate-/, /^inset-/, /^visually-/,
  /^bg-/, /^link-/,
];

/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: [
    // Next.js built-in: autoprefixer is already included — no need to add it.
    // PurgeCSS runs only in production to strip unused rules.
    ...(prod
      ? [
          [
            "@fullhuman/postcss-purgecss",
            {
              content: [
                "./src/**/*.{js,jsx,ts,tsx}",
                "./public/**/*.html",
              ],
              safelist: {
                standard: ["active", "open", "show", "hide", "disabled",
                            "collapsing", "collapsed", "not__found", "activePage"],
                greedy: safelistPatterns,
              },
              // Capture hyphenated class names and Bootstrap's bracket utilities
              defaultExtractor: (content) =>
                content.match(/[\w-:/[\]]+(?<!:)/g) ?? [],
              rejected: false,
            },
          ],
        ]
      : []),
  ],
};

export default config;
