import { getSiteUrl } from "@/config/env";
import { serverGet, unwrapList } from "@/lib/serverFetch";
import { routing } from "@/i18n/routing";

/**
 * Dynamic sitemap.xml.
 *
 * Strategy:
 *   - Static surfaces (home, faq, policies, community/{type}, shops): one
 *     entry per locale.
 *   - Books: paginated via the public list endpoint. Hard-cap at 5000
 *     entries because Next.js' single sitemap file is limited to 50 000
 *     URLs and the file is regenerated on every revalidate window — we
 *     don't want a 30 s response time for crawlers.
 *   - Shops: same pattern, smaller cap.
 *   - Categories: one entry each.
 *   - hreflang: every entry carries alternates for all three locales
 *     so Google can swap the right URL into SERP per user language.
 *
 * The file is regenerated by Next's MetadataRoute runtime when stale.
 * `revalidate` here mirrors backend cadence — books move faster than
 * shops, but a 1-hour TTL keeps the cost bounded.
 *
 * Future: when the catalog passes ~10k books, switch to a sitemap index
 * (sitemap-static.xml + sitemap-books-1.xml…) so each file stays small.
 */
export const revalidate = 3600;

const BOOK_LIMIT = 5000;
const SHOP_LIMIT = 1000;
const STATIC_PATHS = [
  { path: "", priority: 1.0, changeFrequency: "daily" },
  { path: "/community/all", priority: 0.9, changeFrequency: "hourly" },
  { path: "/community/sell", priority: 0.9, changeFrequency: "hourly" },
  { path: "/community/gift", priority: 0.8, changeFrequency: "daily" },
  { path: "/community/exchange", priority: 0.8, changeFrequency: "daily" },
  { path: "/community/rent", priority: 0.7, changeFrequency: "weekly" },
  { path: "/shops", priority: 0.9, changeFrequency: "daily" },
  { path: "/about-us", priority: 0.5, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.5, changeFrequency: "monthly" },
  { path: "/faq", priority: 0.6, changeFrequency: "weekly" },
  { path: "/policies", priority: 0.4, changeFrequency: "monthly" },
];

function localeAlternates(base, path) {
  // Google reads alternates from the sitemap when each variant URL is
  // a separate <url> entry. Next 15+ accepts an `alternates.languages`
  // map on each entry so we can emit them all from one item.
  const languages = {};
  for (const loc of routing.locales) {
    languages[loc] = `${base}/${loc}${path}`;
  }
  // x-default points at the uz canonical (our defaultLocale).
  languages["x-default"] = `${base}/uz${path}`;
  return languages;
}

export default async function sitemap() {
  const base = getSiteUrl().replace(/\/$/, "");
  const now = new Date();

  const entries = [];

  // ── Static surfaces × locales ────────────────────────────────────
  for (const loc of routing.locales) {
    for (const { path, priority, changeFrequency } of STATIC_PATHS) {
      entries.push({
        url: `${base}/${loc}${path}`,
        lastModified: now,
        changeFrequency,
        priority,
        alternates: { languages: localeAlternates(base, path) },
      });
    }
  }

  // ── Books ────────────────────────────────────────────────────────
  // Fetch the most recent books up to BOOK_LIMIT. We page in 200-sized
  // batches because the API caps at 100 server-side; even at 5000 books
  // that's 25 round trips, sequential to keep memory low. The whole
  // sitemap is cached for 1 h so this runs at most once per revalidate
  // window.
  const books = await fetchPaged("/api/v1/book/list/", { limit: 100, is_active: true }, BOOK_LIMIT);
  for (const book of books) {
    if (!book?.id) continue;
    const path = `/book-details/${book.id}`;
    entries.push({
      url: `${base}/uz${path}`,
      lastModified: parseDate(book.updated_at) || parseDate(book.created_at) || now,
      changeFrequency: "weekly",
      priority: 0.7,
      alternates: { languages: localeAlternates(base, path) },
    });
  }

  // ── Shops ────────────────────────────────────────────────────────
  const shops = await fetchPaged("/api/v1/shop/list/", { limit: 100, is_active: true }, SHOP_LIMIT);
  for (const shop of shops) {
    if (!shop?.id) continue;
    const path = `/shops/${shop.id}`;
    entries.push({
      url: `${base}/uz${path}`,
      lastModified: parseDate(shop.updated_at) || parseDate(shop.created_at) || now,
      changeFrequency: "weekly",
      priority: 0.6,
      alternates: { languages: localeAlternates(base, path) },
    });
  }

  return entries;
}

// ── Helpers ──────────────────────────────────────────────────────────

async function fetchPaged(path, baseParams, cap) {
  const results = [];
  let offset = 0;
  const limit = baseParams.limit || 100;
  // Hard upper bound on round trips so a misbehaving backend doesn't
  // spin this forever. Cap = max items; trips = cap / limit + slack.
  const maxTrips = Math.ceil(cap / limit) + 1;
  for (let trip = 0; trip < maxTrips && results.length < cap; trip++) {
    const data = await serverGet(path, {
      params: { ...baseParams, offset, limit },
      revalidate: 3600,
    });
    if (!data) break;
    const { items, count } = unwrapList(data);
    if (!items.length) break;
    results.push(...items);
    if (results.length >= count) break;
    offset += limit;
  }
  return results.slice(0, cap);
}

function parseDate(value) {
  if (!value) return null;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d;
}
