import { getApiBaseUrl, getSupportPhone } from "./env";

export const API_BASE_URL = getApiBaseUrl();

export const SUPPORT_PHONE = getSupportPhone();

// Pages where unauthenticated users should be redirected to /login.
// Everything else is anonymous-readable (home, shops, /community/*, book
// details, policies, faq, etc.). Match by *path suffix* (leaf pages) or
// *path segment* (dynamic routes like `/user/<id>`) so the locale prefix
// (`/uz/account`) still matches.
// `/user` is gated because the backend `/auth/<id>/` endpoint requires auth
// (user-enumeration / H-1 privacy protection) — anonymous visitors would
// otherwise hit a 401→login loop.
export const PROTECTED_PAGES = ["/account", "/wishlist", "/user", "/admin"];

// Legacy export — kept so callers that imported PUBLIC_PAGES still work.
// Login / register surfaces are always reachable by definition; we list them
// here so any leftover `PUBLIC_PAGES.includes(...)` check passes through.
// `/auth/auto` is the bot auto-login interstitial — hide the header there so
// it doesn't fire authenticated background requests (or drive logout) while
// the one-time ticket is being exchanged.
export const PUBLIC_PAGES = ["/login", "/register", "/forgot-password", "/auth/auto"];

export const AUTH_TOKEN_STORAGE_KEY = "auth_token";

// C-4 (partial): the 14-day refresh token lives in an HttpOnly cookie set by
// the backend, NOT in localStorage — so XSS can't exfiltrate it. The backend
// is additive (still accepts a body refresh token), so flipping this to
// `false` + rebuilding cleanly reverts to the old body-token behaviour
// (instant-ish rollback). The short-lived access token stays in localStorage
// + Authorization header, so the rest of the auth flow is unchanged.
export const COOKIE_REFRESH = true;

export const API_ENDPOINTS = {
  AUTH: {
    // Trailing slashes are MANDATORY — Django's APPEND_SLASH issues a 301
    // redirect on missing slash, but POST/PATCH/DELETE redirects either crash
    // with RuntimeError or get downgraded to GET, both of which surface as
    // "GET not allowed" / 500 errors in the FE.
    //
    // OTP is generated by the Telegram bot (POST /auth/bot/otp/, IsMyBot).
    // Web-only OTP request, registration, and logout endpoints do NOT exist
    // on the backend — see back-end/users/urls.py. Registration happens via
    // the bot; logout is local-only since JWT is stateless.
    LOGIN: "api/v1/auth/login/",
    // Code-only sibling: bot-issued OTP is sufficient (no phone step).
    // Backend: users/api_endpoints/LoginByCode/views.py:LoginByCodeAPIView.
    LOGIN_BY_CODE: "api/v1/auth/login-code/",
    REFRESH: "api/v1/auth/refresh/",
    // H-3: Server-side logout blacklists the refresh token so it can't
    // be replayed if it was stolen before the user clicked logout.
    // Backend: users/api_endpoints/Logout/views.py:LogoutAPIView.
    LOGOUT: "api/v1/auth/logout/",
    ME: "api/v1/auth/me/",
    DETAIL: "api/v1/auth", // used as prefix, callers append `/${id}/`
    UPDATE_PROFILE: "api/v1/auth/me/update/",
    TICKET_LOGIN: "api/v1/auth/ticket-login/",
  },
  BOOKS: {
    LIST: "api/v1/book/list/",
    DETAIL: "api/v1/book",
    CATEGORIES: "api/v1/book/categories/",
    CATEGORY_DETAIL: "api/v1/book/categories",
    SUBCATEGORIES: "api/v1/book/subcategories/",
    CREATE: "api/v1/book/create/",
    LIKE: "api/v1/book/like/",
    LIKED: "api/v1/book/liked/",
    COMMENT: {
      CREATE: "api/v1/book/comment/create/",
      LIST: "api/v1/book/comment/list/",
      LIKE: "api/v1/book/comment/like/",
      DELETE: "api/v1/book/comment",
    },
  },
  // Book collections (bundles). The backend lives under the book app
  // (/api/v1/book/collections/...). DETAIL is a prefix — callers append
  // `/${id}/`; membership actions append `/${id}/books/...`.
  COLLECTIONS: {
    LIST: "api/v1/book/collections/list/",
    DETAIL: "api/v1/book/collections", // append `/${id}/`
    CREATE: "api/v1/book/collections/create/",
    UPDATE: "api/v1/book/collections", // append `/${id}/` — PATCH
    DELETE: "api/v1/book/collections", // append `/${id}/` — DELETE
    ADD_BOOK: "api/v1/book/collections", // append `/${id}/books/add/`
    BOOK: "api/v1/book/collections", // append `/${id}/books/${bookId}/` (DELETE) or `.../move/`
  },
  SHOPS: {
    LIST: "api/v1/shop/list/",
    DETAIL: "api/v1/shop", // caller appends `/${id}/`
    CREATE: "api/v1/shop/create/",
    UPDATE: "api/v1/shop", // caller appends `/${id}/` — PATCH
    STAFF: "api/v1/shop/stuff/",
    STAFF_DETAIL: "api/v1/shop/stuff", // caller appends `/${id}/`
    // Shop announcement banners.
    //   POST   /api/v1/shop/banners/           — create (body.shop = shop_id)
    //   PATCH  /api/v1/shop/<banner_id>/banners/ — update single banner
    // The PATCH URL's <pk> is the BANNER id (the path is misleading — the
    // ViewSet resolves get_object() against ShopBanner, not Shop).
    BANNER_CREATE: "api/v1/shop/banners/",
    BANNER_UPDATE: "api/v1/shop", // caller appends `/${banner_id}/banners/`
  },
  STORIES: {
    LIST: "api/v1/stories/",
    DETAIL: "api/v1/stories", // caller appends `/${id}/`
  },
  // PARKED — backend blog app is disabled (back-end/config/urls.py:31).
  // These endpoints currently return 404. Kept here for the planned blog
  // feature so the contract is documented; do NOT call them until backend
  // restores `include('blog.urls')`. See src/services/posts.js for details.
  POSTS: {
    LIST: "api/v1/post/list/",
    DETAIL: "api/v1/post/detail", // prefix — caller appends `/${id}/`
    CREATE: "api/v1/post/create/",
    UPDATE: "api/v1/post/update/", // caller appends `${id}/`
    DELETE: "api/v1/post/delete/", // caller appends `${id}/`
  },
  BASE: {
    REGIONS: "api/v1/base/regions/",
    REGION_DETAIL: "api/v1/base/regions",
    BANNERS: "api/v1/base/banners/",
    BANNER_DETAIL: "api/v1/base/banners",
    FAQS: "api/v1/base/faqs/",
    POLICIES: "api/v1/base/policies/",
    CONTACT: "api/v1/base/contact-us/",
  },
  // Staff-only CEO/Founder dashboard. The backend enforces `IsAdminUser`
  // (is_staff); the /admin route is additionally role-gated client-side for UX.
  ADMIN: {
    SUMMARY: "api/v1/analytics/dashboard/summary/",
    FUNNEL: "api/v1/analytics/dashboard/funnel/",
    DEMAND: "api/v1/analytics/dashboard/demand/",
    SUPPLY: "api/v1/analytics/dashboard/supply/",
  },
};
