import { getApiBaseUrl, getSupportPhone } from "./env";

export const API_BASE_URL = getApiBaseUrl();

export const SUPPORT_PHONE = getSupportPhone();

// Pages where unauthenticated users should be redirected to /login.
// Everything else is anonymous-readable (home, shops, /community/*, book
// details, policies, faq, etc.). Match by *path suffix* (leaf pages) or
// *path segment* (dynamic routes like `/user/<id>`) so the locale prefix
// (`/uz/account`) still matches.
// `/user` is gated because the backend `/auth/<id>/` endpoint requires auth
// (user-enumeration / H-1 privacy protection) — anonymous visitors would
// otherwise hit a 401→login loop.
export const PROTECTED_PAGES = ["/account", "/wishlist", "/user"];

// Legacy export — kept so callers that imported PUBLIC_PAGES still work.
// Login / register surfaces are always reachable by definition; we list them
// here so any leftover `PUBLIC_PAGES.includes(...)` check passes through.
export const PUBLIC_PAGES = ["/login", "/register", "/forgot-password"];

export const AUTH_TOKEN_STORAGE_KEY = "auth_token";

export const API_ENDPOINTS = {
  AUTH: {
    // Trailing slashes are MANDATORY — Django's APPEND_SLASH issues a 301
    // redirect on missing slash, but POST/PATCH/DELETE redirects either crash
    // with RuntimeError or get downgraded to GET, both of which surface as
    // "GET not allowed" / 500 errors in the FE.
    //
    // OTP is generated by the Telegram bot (POST /auth/bot/otp/, IsMyBot).
    // Web-only OTP request, registration, and logout endpoints do NOT exist
    // on the backend — see back-end/users/urls.py. Registration happens via
    // the bot; logout is local-only since JWT is stateless.
    LOGIN: "api/v1/auth/login/",
    // Code-only sibling: bot-issued OTP is sufficient (no phone step).
    // Backend: users/api_endpoints/LoginByCode/views.py:LoginByCodeAPIView.
    LOGIN_BY_CODE: "api/v1/auth/login-code/",
    REFRESH: "api/v1/auth/refresh/",
    // H-3: Server-side logout blacklists the refresh token so it can't
    // be replayed if it was stolen before the user clicked logout.
    // Backend: users/api_endpoints/Logout/views.py:LogoutAPIView.
    LOGOUT: "api/v1/auth/logout/",
    ME: "api/v1/auth/me/",
    DETAIL: "api/v1/auth", // used as prefix, callers append `/${id}/`
    UPDATE_PROFILE: "api/v1/auth/me/update/",
    TICKET_LOGIN: "api/v1/auth/ticket-login/",
  },
  BOOKS: {
    LIST: "api/v1/book/list/",
    DETAIL: "api/v1/book",
    CATEGORIES: "api/v1/book/categories/",
    CATEGORY_DETAIL: "api/v1/book/categories",
    SUBCATEGORIES: "api/v1/book/subcategories/",
    CREATE: "api/v1/book/create/",
    LIKE: "api/v1/book/like/",
    LIKED: "api/v1/book/liked/",
    COMMENT: {
      CREATE: "api/v1/book/comment/create/",
      LIST: "api/v1/book/comment/list/",
      LIKE: "api/v1/book/comment/like/",
      DELETE: "api/v1/book/comment",
    },
  },
  SHOPS: {
    LIST: "api/v1/shop/list/",
    DETAIL: "api/v1/shop", // caller appends `/${id}/`
    CREATE: "api/v1/shop/create/",
    UPDATE: "api/v1/shop", // caller appends `/${id}/` — PATCH
    STAFF: "api/v1/shop/stuff/",
    STAFF_DETAIL: "api/v1/shop/stuff", // caller appends `/${id}/`
    // Shop announcement banners.
    //   POST   /api/v1/shop/banners/           — create (body.shop = shop_id)
    //   PATCH  /api/v1/shop/<banner_id>/banners/ — update single banner
    // The PATCH URL's <pk> is the BANNER id (the path is misleading — the
    // ViewSet resolves get_object() against ShopBanner, not Shop).
    BANNER_CREATE: "api/v1/shop/banners/",
    BANNER_UPDATE: "api/v1/shop", // caller appends `/${banner_id}/banners/`
  },
  STORIES: {
    LIST: "api/v1/stories/",
    DETAIL: "api/v1/stories", // caller appends `/${id}/`
  },
  // PARKED — backend blog app is disabled (back-end/config/urls.py:31).
  // These endpoints currently return 404. Kept here for the planned blog
  // feature so the contract is documented; do NOT call them until backend
  // restores `include('blog.urls')`. See src/services/posts.js for details.
  POSTS: {
    LIST: "api/v1/post/list/",
    DETAIL: "api/v1/post/detail", // prefix — caller appends `/${id}/`
    CREATE: "api/v1/post/create/",
    UPDATE: "api/v1/post/update/", // caller appends `${id}/`
    DELETE: "api/v1/post/delete/", // caller appends `${id}/`
  },
  BASE: {
    REGIONS: "api/v1/base/regions/",
    REGION_DETAIL: "api/v1/base/regions",
    BANNERS: "api/v1/base/banners/",
    BANNER_DETAIL: "api/v1/base/banners",
    FAQS: "api/v1/base/faqs/",
    POLICIES: "api/v1/base/policies/",
    CONTACT: "api/v1/base/contact-us/",
  },
  GIVEAWAY: {
    ACTIVE: "api/v1/book/give-away/active/",
    LIST: "api/v1/give-away/",
    DETAIL: "api/v1/give-away", // prefix
  },
};
